You are given two strings, str1 and str2, of lengths n and m, respectively.
A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:
    If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
    If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".
Example 1:
Input: str1 = "TFTF", str2 = "ab"
Output: "ababa"
Explanation:
  The table below represents the string "ababa"
  Index	T/F	Substring of length m
   0	'T'	"ab"
   1	'F'	"ba"
   2	'T'	"ab"
   3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.
Return "ababa" since it is the lexicographically smaller string.
Example 2:
  Input: str1 = "TFTF", str2 = "abc"
  Output: ""
Explanation:
No string that satisfies the conditions can be generated.

Example 3:
Input: str1 = "F", str2 = "d"
Output: "a"

Constraints:
1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.

Problem Mindset
You are constructing a string under constraints:
  'T' → must match exactly
  'F' → must NOT match
So this is a constraint satisfaction problem.
  Key Idea (Very Important)
    Treat 'T' as hard constraints
    Treat 'F' as soft constraints

Step-by-Step Approach
1. Build the skeleton (handle 'T' first)
   For every index i where str1[i] == 'T':
     You are forced to place str2 at position i
 So:
  res[i + j] = str2[j]
  Conflict check:
     If two 'T' placements overlap and mismatch → impossible
     Immediately return ""

2. Lock those positions 🔒
    All characters placed due to 'T' are:
     fixed / immutable
   Because:
     If you change them later → you break a 'T'
3. Fill remaining positions
     Now some positions are still empty (?)
     Fill them with 'a'
Why?
  We want lexicographically smallest string
4. Fix 'F' constraints
       Now for every i where str1[i] == 'F':
Check:
   Is substring res[i...i+m-1] == str2?
   Case 1: Already different 
           Do nothing
Case 2: Exactly same 
        We must break it
How to break it?
  We need:
    Change at least one character in that substring

BUT:
  Important Rule
  You can ONLY change positions that are NOT locked
  Strategy to break (greedy)
  Try from right → left (safer for lexicographic order)
  Pick a position:
     If not locked
     Change it to smallest char ≠ str2[j]
     If no such position exists

That means:
   Entire substring is locked
   And equals str2
   Impossible → return ""

Why this works
  1. 'T' handled first
     Guarantees all required matches
  2. 'F' handled later
      Only needs at least one mismatch
      Easier to fix
3. Locked positions
    Prevent breaking valid constraints
    Intuition in One Line
First force what must be true,
then carefully break what must not be true,
without touching the forced parts.

Example Insight
 Case:
   str1 = "TTFFT"
   str2 = "fff"
   'T' forces everything → "fffffff"
   'F' wants mismatch → but all positions are locked
No freedom → impossible

Pattern Recognition (for interviews)
This problem is a mix of:
  Greedy construction
  String overlay
  Constraint propagation
  Immutable vs mutable state
Final Takeaway
  If interviewer asks:
  “What is the main idea?”
You say:
  “I first enforce all mandatory matches using 'T' constraints and mark those positions as locked.
  Then I greedily construct the smallest string and fix 'F' constraints by introducing minimal changes only in unlocked positions,
  ensuring I never violate already enforced constraints.”

Implementation:
  class Solution {
    public String generateString(String str1, String str2) {
        int n = str1.length();
        int m = str2.length();
        int len = n + m - 1;

        char[] res = new char[len];
        boolean[] locked = new boolean[len];
        Arrays.fill(res, '?');

        // Step 1: Apply 'T'
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'T') {
                for (int j = 0; j < m; j++) {
                    if (res[i + j] == '?' || res[i + j] == str2.charAt(j)) {
                        res[i + j] = str2.charAt(j);
                        locked[i + j] = true;
                    } else {
                        return "";
                    }
                }
            }
        }

        // Step 2: Fill '?' with 'a'
        for (int i = 0; i < len; i++) {
            if (res[i] == '?') res[i] = 'a';
        }

        // Step 3: Fix 'F'
        for (int i = 0; i < n; i++) {
            if (str1.charAt(i) == 'F') {
                boolean match = true;

                for (int j = 0; j < m; j++) {
                    if (res[i + j] != str2.charAt(j)) {
                        match = false;
                        break;
                    }
                }

                if (match) {
                    boolean fixed = false;

                    // Try to break using ONLY unlocked positions
                    for (int j = m - 1; j >= 0; j--) {
                        int pos = i + j;

                        if (locked[pos]) continue;

                        for (char c = 'a'; c <= 'z'; c++) {
                            if (c != str2.charAt(j)) {
                                res[pos] = c;
                                fixed = true;
                                break;
                            }
                        }

                        if (fixed) break;
                    }

                    if (!fixed) return "";
                }
            }
        }

        return new String(res);
    }
}
